name: scouting_app_2024
description: "Rebel Robotics FRC 2638 Scouting App 2024"
publish_to: "none"
version: 1.0.5+4

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  bloc: ^8.1.2
  build_runner: ^2.4.8
  community_material_icon: ^5.9.55
  confetti: ^0.7.0
  equatable: ^2.0.5
  fl_chart: ^0.66.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg_icons: ^0.0.1+3
  fluttertoast: ^8.2.4
  get: ^4.6.6
  get_storage: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  ionicons: ^0.2.2
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  json_theme: ^6.4.0
  logging: ^1.2.0
  mobile_scanner: ^4.0.0
  multi_dropdown: ^2.1.4
  numberpicker: ^2.1.2
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  photo_view: ^0.14.0
  platform_info: ^4.0.2
  pretty_qr_code: ^3.1.0
  provider: ^6.1.1
  responsive_grid_list: ^1.4.0
  show_fps: ^1.0.6
  sizer: ^2.0.15
  theme_provider: ^0.6.0
  themed: ^5.0.1
  url_launcher: ^6.2.3
  uuid: ^4.3.3
  window_manager: ^0.3.8
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/crescendo/labelled_map.png
    - assets/crescendo/field.png
    - assets/crescendo/high_note.png
    - assets/crescendo/note.png
    - assets/appicon_header.png
    - assets/icons/firstinspires-icon.svg
    - assets/crescendo/crescendo_header.png
    - assets/legals/OFL.txt
    - assets/legals/BSD-4.txt
    - assets/2324_teampic.png
    - assets/2324_teampic_blurred.jpg
    - assets/themes/
    - assets/rules/
    - assets/default_dark.json
    - assets/default_dark_2.json
    - assets/default_light.json
    - assets/default_light_2.json
  fonts:
    - family: IBM Plex Sans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBMPlexSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/IBMPlexSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/IBMPlexSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/IBMPlexSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/IBMPlexSans-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/IBMPlexSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/IBMPlexSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/IBMPlexSans-ThinItalic.ttf
          weight: 100
          style: italic
    - family: IBM Plex Mono
      fonts:
        - asset: assets/fonts/mono/IBMPlexMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/mono/IBMPlexMono-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/mono/IBMPlexMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/mono/IBMPlexMono-Italic.ttf
          weight: 400
          style: italic
